language: php

php:
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update

install: composer update --prefer-source

script:
  - make qualimetry
