language: php

php:
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/yarn

before_install:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update

install:
  - composer install --verbose --prefer-dist --optimize-autoloader --no-progress --no-interaction
  - yarn install

script:
  - make qualimetry
  - yarn run encore production
